---
- name: Create Homer directory
  file:
    path: /home/pi/homer
    state: directory
    owner: pi
    group: pi
    mode: '0755'

- name: Download Homer
  get_url:
    url: "https://github.com/bastienwirtz/homer/releases/download/v23.10.1/homer.zip"
    dest: /tmp/homer.zip
    mode: '0644'

- name: Extract Homer
  unarchive:
    src: /tmp/homer.zip
    dest: /home/pi/homer
    remote_src: yes
    owner: pi
    group: pi

- name: Deploy Homer configuration
  template:
    src: config.yml.j2
    dest: /home/pi/homer/assets/config.yml
    owner: pi
    group: pi
    mode: '0644'
  notify: restart homer

- name: Deploy Homer systemd service
  template:
    src: homer.service.j2
    dest: /etc/systemd/system/homer.service
    mode: '0644'
  notify:
    - reload systemd
    - restart homer

- name: Enable Homer service
  systemd:
    name: homer
    enabled: yes
    daemon_reload: yes
    state: started
